#!/bin/bash
python3 datasync_retry.py --arn_file="arn_file.txt" --timeout_sec="10"
